

const authToken = async (req, res, next) => {

  // TODO - FAZER AGORA ESSE MIDLEWARE QUE VALIDA O TOKEN, LEMBRANDO QUE TEMPORARIAMENTE ELE FICA NO ARQUIVO NA PASTA CRIADA (NO CONTAINER DOCKER)
  
}