// COMPLETE RESPONSE:

// TODO - TEMOS O DIA, CADA DIA TEM VÁRIOS OBJ PARA CADA HORA, TEMOS QUE ITERAR SOBRE CADA UM DE FORMA QUE FAÇA ISSO INDEPENDENTE DE QUANTOS DIAS SÃO
// TODO - O RESTO É LOCATION, CURRENT (QUE CONTÉM A CONDIÇÃO ATUAL), E O FORECAST, QUE CONTÉM OS DIAS COM CADA HORA COMO EU DISSE
const obj = {
  location: {
    name: "Paris",
    region: "Ile-de-France",
    country: "France",
    lat: 48.8667,
    lon: 2.3333,
    tz_id: "Europe/Paris",
    localtime_epoch: 1768572958,
    localtime: "2026-01-16 15:15",
  },
  current: {
    last_updated_epoch: 1768572900,
    last_updated: "2026-01-16 15:15",
    temp_c: 11.1,
    temp_f: 52,
    is_day: 1,
    condition: {
      text: "Parcialmente nublado",
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      code: 1003,
    },
    wind_mph: 5.8,
    wind_kph: 9.4,
    wind_degree: 159,
    wind_dir: "SSE",
    pressure_mb: 1012,
    pressure_in: 29.88,
    precip_mm: 0,
    precip_in: 0,
    humidity: 71,
    cloud: 75,
    feelslike_c: 10.1,
    feelslike_f: 50.1,
    windchill_c: 9.4,
    windchill_f: 49,
    heatindex_c: 10.6,
    heatindex_f: 51,
    dewpoint_c: 6.2,
    dewpoint_f: 43.2,
    vis_km: 10,
    vis_miles: 6,
    uv: 0.4,
    gust_mph: 7.7,
    gust_kph: 12.5,
  },
  forecast: {
    forecastday: [
      {
        date: "2026-01-16",
        date_epoch: 1768521600,
        day: {
          maxtemp_c: 10.6,
          maxtemp_f: 51,
          mintemp_c: 6.1,
          mintemp_f: 43,
          avgtemp_c: 8.5,
          avgtemp_f: 47.4,
          maxwind_mph: 10.3,
          maxwind_kph: 16.6,
          totalprecip_mm: 0.56,
          totalprecip_in: 0.02,
          totalsnow_cm: 0,
          avgvis_km: 9.7,
          avgvis_miles: 6,
          avghumidity: 83,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 88,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Possibilidade de chuva irregular",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 0.1,
        },
        astro: {
          sunrise: "08:38 AM",
          sunset: "05:23 PM",
          moonrise: "07:30 AM",
          moonset: "02:38 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: 8,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1768518000,
            time: "2026-01-16 00:00",
            temp_c: 9.2,
            temp_f: 48.5,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 226,
            wind_dir: "SW",
            pressure_mb: 1009,
            pressure_in: 29.8,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 74,
            cloud: 72,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 9.2,
            heatindex_f: 48.5,
            dewpoint_c: 4.8,
            dewpoint_f: 40.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.5,
            gust_kph: 23.3,
            uv: 0,
          },
          {
            time_epoch: 1768521600,
            time: "2026-01-16 01:00",
            temp_c: 8.9,
            temp_f: 48,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 212,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.81,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 78,
            cloud: 48,
            feelslike_c: 6.7,
            feelslike_f: 44,
            windchill_c: 6.7,
            windchill_f: 44,
            heatindex_c: 8.9,
            heatindex_f: 48.1,
            dewpoint_c: 5.2,
            dewpoint_f: 41.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.9,
            gust_kph: 20.7,
            uv: 0,
          },
          {
            time_epoch: 1768525200,
            time: "2026-01-16 02:00",
            temp_c: 8.7,
            temp_f: 47.6,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 200,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 33,
            feelslike_c: 6.5,
            feelslike_f: 43.7,
            windchill_c: 6.5,
            windchill_f: 43.7,
            heatindex_c: 8.7,
            heatindex_f: 47.6,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12,
            gust_kph: 19.4,
            uv: 0,
          },
          {
            time_epoch: 1768528800,
            time: "2026-01-16 03:00",
            temp_c: 8.4,
            temp_f: 47.2,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 202,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 81,
            cloud: 66,
            feelslike_c: 6.5,
            feelslike_f: 43.7,
            windchill_c: 6.5,
            windchill_f: 43.7,
            heatindex_c: 8.4,
            heatindex_f: 47.2,
            dewpoint_c: 5.4,
            dewpoint_f: 41.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 0,
          },
          {
            time_epoch: 1768532400,
            time: "2026-01-16 04:00",
            temp_c: 7.9,
            temp_f: 46.2,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 198,
            wind_dir: "SSW",
            pressure_mb: 1010,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 83,
            cloud: 37,
            feelslike_c: 6.3,
            feelslike_f: 43.3,
            windchill_c: 6.3,
            windchill_f: 43.3,
            heatindex_c: 7.9,
            heatindex_f: 46.2,
            dewpoint_c: 5.2,
            dewpoint_f: 41.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 0,
          },
          {
            time_epoch: 1768536000,
            time: "2026-01-16 05:00",
            temp_c: 7.3,
            temp_f: 45.2,
            is_day: 0,
            condition: {
              text: "Céu limpo",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 187,
            wind_dir: "S",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 16,
            feelslike_c: 5.9,
            feelslike_f: 42.5,
            windchill_c: 5.9,
            windchill_f: 42.5,
            heatindex_c: 7.3,
            heatindex_f: 45.2,
            dewpoint_c: 4.8,
            dewpoint_f: 40.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.2,
            gust_kph: 13.1,
            uv: 0,
          },
          {
            time_epoch: 1768539600,
            time: "2026-01-16 06:00",
            temp_c: 6.8,
            temp_f: 44.2,
            is_day: 0,
            condition: {
              text: "Céu limpo",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 183,
            wind_dir: "S",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 10,
            feelslike_c: 5.4,
            feelslike_f: 41.8,
            windchill_c: 5.4,
            windchill_f: 41.8,
            heatindex_c: 6.8,
            heatindex_f: 44.2,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.4,
            uv: 0,
          },
          {
            time_epoch: 1768543200,
            time: "2026-01-16 07:00",
            temp_c: 6.5,
            temp_f: 43.7,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 176,
            wind_dir: "S",
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 38,
            feelslike_c: 5,
            feelslike_f: 41,
            windchill_c: 5,
            windchill_f: 41,
            heatindex_c: 6.5,
            heatindex_f: 43.7,
            dewpoint_c: 4.7,
            dewpoint_f: 40.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 0,
          },
          {
            time_epoch: 1768546800,
            time: "2026-01-16 08:00",
            temp_c: 6.3,
            temp_f: 43.3,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 182,
            wind_dir: "S",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 90,
            cloud: 31,
            feelslike_c: 4.7,
            feelslike_f: 40.5,
            windchill_c: 4.7,
            windchill_f: 40.5,
            heatindex_c: 6.3,
            heatindex_f: 43.3,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.4,
            uv: 0,
          },
          {
            time_epoch: 1768550400,
            time: "2026-01-16 09:00",
            temp_c: 6.1,
            temp_f: 43,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 29,
            feelslike_c: 4.5,
            feelslike_f: 40.1,
            windchill_c: 4.5,
            windchill_f: 40.1,
            heatindex_c: 6.1,
            heatindex_f: 43,
            dewpoint_c: 4.8,
            dewpoint_f: 40.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 0,
          },
          {
            time_epoch: 1768554000,
            time: "2026-01-16 10:00",
            temp_c: 7,
            temp_f: 44.6,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 30,
            feelslike_c: 5.5,
            feelslike_f: 41.8,
            windchill_c: 5.5,
            windchill_f: 41.8,
            heatindex_c: 7,
            heatindex_f: 44.7,
            dewpoint_c: 5.4,
            dewpoint_f: 41.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.2,
            gust_kph: 13.1,
            uv: 0.3,
          },
          {
            time_epoch: 1768557600,
            time: "2026-01-16 11:00",
            temp_c: 8.3,
            temp_f: 46.9,
            is_day: 1,
            condition: {
              text: "Sol",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 180,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 25,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 8.3,
            heatindex_f: 46.9,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.9,
            gust_kph: 12.7,
            uv: 0.5,
          },
          {
            time_epoch: 1768561200,
            time: "2026-01-16 12:00",
            temp_c: 9.2,
            temp_f: 48.6,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 173,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 37,
            feelslike_c: 7.7,
            feelslike_f: 45.8,
            windchill_c: 7.7,
            windchill_f: 45.8,
            heatindex_c: 9.2,
            heatindex_f: 48.6,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 0.7,
          },
          {
            time_epoch: 1768564800,
            time: "2026-01-16 13:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 171,
            wind_dir: "S",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 77,
            cloud: 79,
            feelslike_c: 8.3,
            feelslike_f: 47,
            windchill_c: 8.3,
            windchill_f: 47,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            dewpoint_c: 6,
            dewpoint_f: 42.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.6,
            gust_kph: 13.8,
            uv: 0.7,
          },
          {
            time_epoch: 1768568400,
            time: "2026-01-16 14:00",
            temp_c: 10.4,
            temp_f: 50.6,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 166,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 75,
            cloud: 76,
            feelslike_c: 8.8,
            feelslike_f: 47.9,
            windchill_c: 8.8,
            windchill_f: 47.9,
            heatindex_c: 10.4,
            heatindex_f: 50.6,
            dewpoint_c: 6.1,
            dewpoint_f: 43.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 0.6,
          },
          {
            time_epoch: 1768572000,
            time: "2026-01-16 15:00",
            temp_c: 11.1,
            temp_f: 52,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 159,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 71,
            cloud: 75,
            feelslike_c: 9.4,
            feelslike_f: 49,
            windchill_c: 9.4,
            windchill_f: 49,
            heatindex_c: 10.6,
            heatindex_f: 51,
            dewpoint_c: 6.2,
            dewpoint_f: 43.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.5,
            uv: 0.4,
          },
          {
            time_epoch: 1768575600,
            time: "2026-01-16 16:00",
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 146,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0.04,
            precip_in: 0,
            snow_cm: 0,
            humidity: 76,
            cloud: 75,
            feelslike_c: 9.3,
            feelslike_f: 48.8,
            windchill_c: 9.3,
            windchill_f: 48.8,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            dewpoint_c: 6.3,
            dewpoint_f: 43.3,
            will_it_rain: 1,
            chance_of_rain: 71,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 0.2,
          },
          {
            time_epoch: 1768579200,
            time: "2026-01-16 17:00",
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 144,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0.09,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 69,
            feelslike_c: 8.6,
            feelslike_f: 47.4,
            windchill_c: 8.6,
            windchill_f: 47.4,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 0,
          },
          {
            time_epoch: 1768582800,
            time: "2026-01-16 18:00",
            temp_c: 9.3,
            temp_f: 48.8,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 154,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.88,
            precip_mm: 0.09,
            precip_in: 0,
            snow_cm: 0,
            humidity: 82,
            cloud: 100,
            feelslike_c: 8,
            feelslike_f: 46.3,
            windchill_c: 8,
            windchill_f: 46.3,
            heatindex_c: 9.4,
            heatindex_f: 48.8,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.8,
            gust_kph: 14.1,
            uv: 0,
          },
          {
            time_epoch: 1768586400,
            time: "2026-01-16 19:00",
            temp_c: 9.1,
            temp_f: 48.4,
            is_day: 0,
            condition: {
              text: "Chuvisco",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 161,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.17,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 84,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46,
            windchill_c: 7.8,
            windchill_f: 46,
            heatindex_c: 9.1,
            heatindex_f: 48.4,
            dewpoint_c: 6.6,
            dewpoint_f: 43.8,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 0,
          },
          {
            time_epoch: 1768590000,
            time: "2026-01-16 20:00",
            temp_c: 8.9,
            temp_f: 48,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 153,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.09,
            precip_in: 0,
            snow_cm: 0,
            humidity: 86,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46,
            windchill_c: 7.8,
            windchill_f: 46,
            heatindex_c: 8.9,
            heatindex_f: 48,
            dewpoint_c: 6.7,
            dewpoint_f: 44,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 0,
          },
          {
            time_epoch: 1768593600,
            time: "2026-01-16 21:00",
            temp_c: 8.7,
            temp_f: 47.7,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 145,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.02,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 7.8,
            feelslike_f: 46,
            windchill_c: 7.8,
            windchill_f: 46,
            heatindex_c: 8.7,
            heatindex_f: 47.7,
            dewpoint_c: 6.7,
            dewpoint_f: 44.1,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 0,
          },
          {
            time_epoch: 1768597200,
            time: "2026-01-16 22:00",
            temp_c: 8.6,
            temp_f: 47.5,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 142,
            wind_dir: "SE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.03,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 100,
            feelslike_c: 7.5,
            feelslike_f: 45.4,
            windchill_c: 7.5,
            windchill_f: 45.4,
            heatindex_c: 8.6,
            heatindex_f: 47.5,
            dewpoint_c: 6.7,
            dewpoint_f: 44.1,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 0,
          },
          {
            time_epoch: 1768600800,
            time: "2026-01-16 23:00",
            temp_c: 8.6,
            temp_f: 47.5,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 153,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 7.2,
            feelslike_f: 44.9,
            windchill_c: 7.2,
            windchill_f: 44.9,
            heatindex_c: 8.6,
            heatindex_f: 47.5,
            dewpoint_c: 6.7,
            dewpoint_f: 44,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.9,
            gust_kph: 12.8,
            uv: 0,
          },
        ],
      },
      {
        date: "2026-01-17",
        date_epoch: 1768608000,
        day: {
          maxtemp_c: 11.1,
          maxtemp_f: 52,
          mintemp_c: 7,
          mintemp_f: 44.6,
          avgtemp_c: 8.6,
          avgtemp_f: 47.4,
          maxwind_mph: 6.5,
          maxwind_kph: 10.4,
          totalprecip_mm: 0.46,
          totalprecip_in: 0.02,
          totalsnow_cm: 0,
          avgvis_km: 9.3,
          avgvis_miles: 5,
          avghumidity: 85,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 85,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Possibilidade de chuva irregular",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 0.1,
        },
        astro: {
          sunrise: "08:37 AM",
          sunset: "05:25 PM",
          moonrise: "08:16 AM",
          moonset: "03:40 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: 3,
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1768604400,
            time: "2026-01-17 00:00",
            temp_c: 8.6,
            temp_f: 47.5,
            is_day: 0,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 153,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 7.2,
            feelslike_f: 45,
            windchill_c: 7.2,
            windchill_f: 45,
            heatindex_c: 8.6,
            heatindex_f: 47.5,
            dewpoint_c: 6.6,
            dewpoint_f: 43.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.7,
            gust_kph: 12.3,
            uv: 0,
          },
          {
            time_epoch: 1768608000,
            time: "2026-01-17 01:00",
            temp_c: 8.5,
            temp_f: 47.3,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 154,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.02,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 100,
            feelslike_c: 7.1,
            feelslike_f: 44.8,
            windchill_c: 7.1,
            windchill_f: 44.8,
            heatindex_c: 8.5,
            heatindex_f: 47.3,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.5,
            uv: 0,
          },
          {
            time_epoch: 1768611600,
            time: "2026-01-17 02:00",
            temp_c: 8.3,
            temp_f: 47,
            is_day: 0,
            condition: {
              text: "Chuvisco",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 156,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.15,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 90,
            cloud: 100,
            feelslike_c: 7.2,
            feelslike_f: 45,
            windchill_c: 7.2,
            windchill_f: 45,
            heatindex_c: 8.3,
            heatindex_f: 47,
            dewpoint_c: 6.7,
            dewpoint_f: 44.1,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.5,
            gust_kph: 10.5,
            uv: 0,
          },
          {
            time_epoch: 1768615200,
            time: "2026-01-17 03:00",
            temp_c: 8.1,
            temp_f: 46.6,
            is_day: 0,
            condition: {
              text: "Chuvisco",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 163,
            wind_dir: "SSE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.16,
            precip_in: 0.01,
            snow_cm: 0,
            humidity: 92,
            cloud: 100,
            feelslike_c: 6.9,
            feelslike_f: 44.4,
            windchill_c: 6.9,
            windchill_f: 44.4,
            heatindex_c: 8.1,
            heatindex_f: 46.6,
            dewpoint_c: 6.9,
            dewpoint_f: 44.4,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 0,
          },
          {
            time_epoch: 1768618800,
            time: "2026-01-17 04:00",
            temp_c: 8.1,
            temp_f: 46.5,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 177,
            wind_dir: "S",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0.09,
            precip_in: 0,
            snow_cm: 0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 7.1,
            feelslike_f: 44.8,
            windchill_c: 7.1,
            windchill_f: 44.8,
            heatindex_c: 8.1,
            heatindex_f: 46.5,
            dewpoint_c: 7,
            dewpoint_f: 44.6,
            will_it_rain: 1,
            chance_of_rain: 100,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 0,
          },
          {
            time_epoch: 1768622400,
            time: "2026-01-17 05:00",
            temp_c: 8,
            temp_f: 46.4,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 181,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 7,
            feelslike_f: 44.5,
            windchill_c: 7,
            windchill_f: 44.5,
            heatindex_c: 8,
            heatindex_f: 46.4,
            dewpoint_c: 6.9,
            dewpoint_f: 44.5,
            will_it_rain: 1,
            chance_of_rain: 76,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.2,
            gust_kph: 10,
            uv: 0,
          },
          {
            time_epoch: 1768626000,
            time: "2026-01-17 06:00",
            temp_c: 7.8,
            temp_f: 46.1,
            is_day: 0,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 188,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 92,
            cloud: 97,
            feelslike_c: 7.2,
            feelslike_f: 44.9,
            windchill_c: 7.2,
            windchill_f: 44.9,
            heatindex_c: 7.8,
            heatindex_f: 46.1,
            dewpoint_c: 6.7,
            dewpoint_f: 44,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.1,
            uv: 0,
          },
          {
            time_epoch: 1768629600,
            time: "2026-01-17 07:00",
            temp_c: 7.3,
            temp_f: 45.1,
            is_day: 0,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 179,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 94,
            cloud: 100,
            feelslike_c: 6.4,
            feelslike_f: 43.6,
            windchill_c: 6.4,
            windchill_f: 43.6,
            heatindex_c: 7.3,
            heatindex_f: 45.1,
            dewpoint_c: 6.4,
            dewpoint_f: 43.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 0,
          },
          {
            time_epoch: 1768633200,
            time: "2026-01-17 08:00",
            temp_c: 7.2,
            temp_f: 45,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 185,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0.01,
            precip_in: 0,
            snow_cm: 0,
            humidity: 93,
            cloud: 87,
            feelslike_c: 6.6,
            feelslike_f: 43.8,
            windchill_c: 6.6,
            windchill_f: 43.8,
            heatindex_c: 7.2,
            heatindex_f: 45,
            dewpoint_c: 6.1,
            dewpoint_f: 42.9,
            will_it_rain: 0,
            chance_of_rain: 66,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 0,
          },
          {
            time_epoch: 1768636800,
            time: "2026-01-17 09:00",
            temp_c: 7.4,
            temp_f: 45.2,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 160,
            wind_dir: "SSE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 91,
            cloud: 50,
            feelslike_c: 7,
            feelslike_f: 44.6,
            windchill_c: 7,
            windchill_f: 44.6,
            heatindex_c: 7.4,
            heatindex_f: 45.2,
            dewpoint_c: 5.9,
            dewpoint_f: 42.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 0,
          },
          {
            time_epoch: 1768640400,
            time: "2026-01-17 10:00",
            temp_c: 7.9,
            temp_f: 46.2,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 137,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 43,
            feelslike_c: 7.5,
            feelslike_f: 45.5,
            windchill_c: 7.5,
            windchill_f: 45.5,
            heatindex_c: 7.9,
            heatindex_f: 46.2,
            dewpoint_c: 6.2,
            dewpoint_f: 43.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.4,
            gust_kph: 7.1,
            uv: 0.1,
          },
          {
            time_epoch: 1768644000,
            time: "2026-01-17 11:00",
            temp_c: 8.7,
            temp_f: 47.7,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 131,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 29.99,
            precip_mm: 0.02,
            precip_in: 0,
            snow_cm: 0,
            humidity: 85,
            cloud: 79,
            feelslike_c: 8.1,
            feelslike_f: 46.6,
            windchill_c: 8.1,
            windchill_f: 46.6,
            heatindex_c: 8.7,
            heatindex_f: 47.7,
            dewpoint_c: 6.4,
            dewpoint_f: 43.6,
            will_it_rain: 1,
            chance_of_rain: 83,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.8,
            uv: 0.4,
          },
          {
            time_epoch: 1768647600,
            time: "2026-01-17 12:00",
            temp_c: 9.7,
            temp_f: 49.4,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 139,
            wind_dir: "SE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 80,
            cloud: 33,
            feelslike_c: 8.9,
            feelslike_f: 48,
            windchill_c: 8.9,
            windchill_f: 48,
            heatindex_c: 9.7,
            heatindex_f: 49.4,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 0.7,
          },
          {
            time_epoch: 1768651200,
            time: "2026-01-17 13:00",
            temp_c: 10.5,
            temp_f: 50.8,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 138,
            wind_dir: "SE",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 76,
            cloud: 67,
            feelslike_c: 9.5,
            feelslike_f: 49.1,
            windchill_c: 9.5,
            windchill_f: 49.1,
            heatindex_c: 10.5,
            heatindex_f: 50.8,
            dewpoint_c: 6.4,
            dewpoint_f: 43.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.2,
            uv: 0.8,
          },
          {
            time_epoch: 1768654800,
            time: "2026-01-17 14:00",
            temp_c: 11,
            temp_f: 51.8,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 127,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 71,
            cloud: 55,
            feelslike_c: 10,
            feelslike_f: 49.9,
            windchill_c: 10,
            windchill_f: 49.9,
            heatindex_c: 11,
            heatindex_f: 51.8,
            dewpoint_c: 6,
            dewpoint_f: 42.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 0.7,
          },
          {
            time_epoch: 1768658400,
            time: "2026-01-17 15:00",
            temp_c: 11.1,
            temp_f: 52,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 111,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 69,
            cloud: 51,
            feelslike_c: 10,
            feelslike_f: 50.1,
            windchill_c: 10,
            windchill_f: 50.1,
            heatindex_c: 11.1,
            heatindex_f: 52,
            dewpoint_c: 5.7,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12,
            uv: 0.4,
          },
          {
            time_epoch: 1768662000,
            time: "2026-01-17 16:00",
            temp_c: 10.9,
            temp_f: 51.7,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 109,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 70,
            cloud: 56,
            feelslike_c: 10.1,
            feelslike_f: 50.1,
            windchill_c: 10.1,
            windchill_f: 50.1,
            heatindex_c: 10.9,
            heatindex_f: 51.7,
            dewpoint_c: 5.7,
            dewpoint_f: 42.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.1,
            gust_kph: 11.4,
            uv: 0.2,
          },
          {
            time_epoch: 1768665600,
            time: "2026-01-17 17:00",
            temp_c: 9.9,
            temp_f: 49.7,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 98,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 74,
            cloud: 51,
            feelslike_c: 8.6,
            feelslike_f: 47.4,
            windchill_c: 8.6,
            windchill_f: 47.4,
            heatindex_c: 9.9,
            heatindex_f: 49.7,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 0,
          },
          {
            time_epoch: 1768669200,
            time: "2026-01-17 18:00",
            temp_c: 8.9,
            temp_f: 47.9,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 79,
            cloud: 34,
            feelslike_c: 7.4,
            feelslike_f: 45.3,
            windchill_c: 7.4,
            windchill_f: 45.3,
            heatindex_c: 8.9,
            heatindex_f: 47.9,
            dewpoint_c: 5.5,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.2,
            gust_kph: 16.5,
            uv: 0,
          },
          {
            time_epoch: 1768672800,
            time: "2026-01-17 19:00",
            temp_c: 8.4,
            temp_f: 47.1,
            is_day: 0,
            condition: {
              text: "Céu limpo",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 80,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 84,
            cloud: 25,
            feelslike_c: 6.7,
            feelslike_f: 44.1,
            windchill_c: 6.7,
            windchill_f: 44.1,
            heatindex_c: 8.4,
            heatindex_f: 47.1,
            dewpoint_c: 5.8,
            dewpoint_f: 42.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17.1,
            uv: 0,
          },
          {
            time_epoch: 1768676400,
            time: "2026-01-17 20:00",
            temp_c: 8,
            temp_f: 46.4,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 81,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 87,
            cloud: 32,
            feelslike_c: 6.3,
            feelslike_f: 43.3,
            windchill_c: 6.3,
            windchill_f: 43.3,
            heatindex_c: 8,
            heatindex_f: 46.4,
            dewpoint_c: 5.9,
            dewpoint_f: 42.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.6,
            gust_kph: 17,
            uv: 0,
          },
          {
            time_epoch: 1768680000,
            time: "2026-01-17 21:00",
            temp_c: 7.5,
            temp_f: 45.6,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 82,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 88,
            cloud: 26,
            feelslike_c: 5.7,
            feelslike_f: 42.2,
            windchill_c: 5.7,
            windchill_f: 42.2,
            heatindex_c: 7.5,
            heatindex_f: 45.6,
            dewpoint_c: 5.7,
            dewpoint_f: 42.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.2,
            gust_kph: 18.1,
            uv: 0,
          },
          {
            time_epoch: 1768683600,
            time: "2026-01-17 22:00",
            temp_c: 7.1,
            temp_f: 44.9,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 83,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 89,
            cloud: 33,
            feelslike_c: 5.1,
            feelslike_f: 41.3,
            windchill_c: 5.1,
            windchill_f: 41.3,
            heatindex_c: 7.2,
            heatindex_f: 44.9,
            dewpoint_c: 5.5,
            dewpoint_f: 41.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 0,
          },
          {
            time_epoch: 1768687200,
            time: "2026-01-17 23:00",
            temp_c: 7,
            temp_f: 44.6,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            snow_cm: 0,
            humidity: 90,
            cloud: 33,
            feelslike_c: 5,
            feelslike_f: 41.1,
            windchill_c: 5,
            windchill_f: 41.1,
            heatindex_c: 7,
            heatindex_f: 44.6,
            dewpoint_c: 5.5,
            dewpoint_f: 41.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.2,
            gust_kph: 18,
            uv: 0,
          },
        ],
      },
    ],
  },
};
